services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/szilamer/.n8n
    region: frankfurt
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_HOST
        fromService:
          name: n8n
          type: web
          property: host
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: N8N_PORT
        value: "5678"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: PATH
        value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - key: N8N_USER_FOLDER
        value: "/home/node/.n8n"
      - key: DB_TYPE
        value: sqlite
      - key: DB_PATH
        value: "/home/node/.n8n/database.sqlite"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10 